### ISSUE TITLE
File upload?

### ISSUE THREAD

**Issue by saschafoerster** [flipswitchingmonkey/n8n-nodes-lexoffice-api#2]
Does file upload work? Maybe I am not able to transmit the binary from a former node or maybe it is just not working? I wonder that there is not field to enter or link the name of the binary. 

When I try to upload, I get error 500: 
<img width="1492" alt="Bildschirm­foto 2023-01-28 um 17 31 12" src="https://user-images.githubusercontent.com/1153741/215277868-b78cb95c-0224-4284-9bd0-0ad2a5a77768.png">

```

NodeApiError: The service was not able to process your request
    at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-lexoffice-api/nodes/LexofficePuplicApi/LexofficePuplicApi.node.ts:145:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:658:28)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:585:53
```

**Comment by flipswitchingmonkey** [comment]
It's probably not implemented  :( 
Tbh. I got sidetracked with other issues and now my lexoffice trial has run out, I've lost access to the API :) I hope to get around to working on it further....

**Comment by saschafoerster** [comment]
Ah, sad. I guess it's one of the most interesting functions of them all. :) At least for me. I now have a workaround by sending them via mail to another service, that uploads PDFs to LexOffice. 
For the API, there is no problem: i regularly created new test-accounts, even with the same e-mail-adress, for testing-purposes. There is no real limit in testing (just everything will be reset, so there are no old files or clients in LexOffice)

**Comment by flipswitchingmonkey** [comment]
oh that's good to know! In that case I'll make sure to carve out some time to look into it.

**Comment by flipswitchingmonkey** [comment]
I just published v0.1.3, which hopefully has a working file upload now... let me know if it works for you

**Comment by pablopaul** [comment]
@saschafoerster 

> I now have a workaround by sending them via mail to another service, that uploads PDFs to LexOffice.

What service have you used?

**Comment by saschafoerster** [comment]
@pablopaul I am using https://github.com/gruessung/send2lex

**Comment by marcoraddatz** [comment]
I integrated it today and it works perfectly fine 🥳 

As reference, this is how I did it:
![Image](https://github.com/user-attachments/assets/0b3564c4-8764-45cd-bb54-fa054ce14529)

Thanks @flipswitchingmonkey for the integration!
